#!/usr/bin/env python3
"""Unbiased off-policy evaluation of an Iono option re-ranker -- zero gate time.

Why this exists
---------------
Round 1 of the gputrain lane trained an option-conditioned Q head on
``episodes/iono_bc_v2`` and rejected it. The reason was *identification*, not
capacity: chosen-action-only logs observe the outcome only at ``a = pi(s)``, so
no offline model can rank the options the rule agent never takes.

Round 2 fixed that with ``collect_iono_decisions.py --explore-eps E``, which
deviates to a uniformly random legal option on a fraction E of eligible
decisions. That makes the log a **contextual bandit dataset with known
propensities**, so a candidate re-ranker can be scored *before* spending any
gate time on it. Round 2 also proved the option axis carries large signal
(each random deviation costs ~20% of win odds), but a large cost of degradation
only bounds the rule policy from below -- it says nothing about the room above
it. This script measures the room above it.

The behaviour policy
--------------------
At an eligible decision (single selection, ``n = len(options) > 1``) the
collector draws a deviation coin with probability ``eps``; on a hit it draws
``alt`` uniformly from all ``n`` options and only deviates if ``alt != r``
(the rule pick). Therefore, exactly:

    p_b(r | s)  = 1 - eps * (n - 1) / n        (the rule pick)
    p_b(a | s)  = eps / n        for every a != r

Both are known in closed form, which is what makes everything below unbiased.
Note the consequence that the deviated action is uniform over the ``n - 1``
*non-rule* options, so the explored subset alone has **zero coverage of the
rule action** -- a naive SNIPS of ``pi = tomato`` on deviations only is
undefined. The non-deviated decisions supply that arm, which is why this
estimator uses *every* eligible decision, not just the explored ones.

The estimand
------------
One-step (single-decision) advantage of a candidate policy over the rule policy,
on the state distribution the rule policy actually visits:

    A(pi) = E_{s ~ d_b, eligible} [ Q^b(s, pi(s)) - Q^b(s, r(s)) ]

``Q^b(s, a)`` = P(win | take a at s, then continue under the behaviour policy).
The logged game outcome is an unbiased draw from it, because after any decision
the rest of the trajectory is generated by the behaviour policy regardless of
which action was taken.

The estimator
-------------
Per eligible decision i, with taken action ``a_i``, rule pick ``r_i``, outcome
``y_i``, and a variance-reduction constant ``b``:

    w_i = pi(a_i | s_i) / p_b(a_i | s_i)  -  1{a_i = r_i} / p_b(r_i | s_i)
    A^  = mean_i [ w_i * (y_i - b) ]

``E[w_i] = 0`` for every i, so subtracting the constant ``b`` cannot bias the
estimate but removes most of its variance. Decisions where ``pi`` agrees with
the rule pick contribute exactly 0, as they should. Standard errors are
**clustered by game**: decisions inside one game share ``y_i`` and are
correlated, so games are the independent unit.

Two reported scales:
  * ``per_decision`` -- A^ itself, win-probability change per eligible decision.
  * ``per_game``     -- the sum over a game's eligible decisions, i.e. the
    first-order estimate of switching the policy everywhere. This is the number
    to compare against the ship gap, but it is a *linear* extrapolation of a
    one-step advantage: it ignores the state-distribution shift a full switch
    would cause. Treat it as a screen, never as a gate result.

Self-tests (``--self-test``) pin the estimator against known answers:
  * ``tomato``        -> exactly 0.0 by construction.
  * ``anti_uniform``  -> uniform over the non-rule options. This is precisely
    the intervention the round-2 dose-response measured, so A^ must reproduce
    the per-deviation cost (~ -4.2pp) that was measured by whole-run win-rate
    differences. Two independent estimators, one number.
  * ``uniform``       -> uniform over all n options = ((n-1)/n) * anti_uniform.

Usage
-----
  python scripts/iono_ips_ope.py --self-test
  python scripts/iono_ips_ope.py --self-test --eps 0.05
  python scripts/iono_ips_ope.py --ckpt artifacts/iono_ips_ranker.pt --split holdout
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

N_STATE = 25
N_OPTION = 21
CACHE = ROOT / "artifacts" / "iono_explore_bandit.npz"


@dataclass
class Bandit:
    """Flat, ragged-free view of every eligible decision in the explore log."""

    S: np.ndarray        # (M, N_STATE)   state features
    O: np.ndarray        # (T, N_OPTION)  every option of every decision, packed
    off: np.ndarray      # (M,) int64     start of decision i inside O
    n: np.ndarray        # (M,) int32     option count of decision i
    a: np.ndarray        # (M,) int32     option index actually taken
    r: np.ndarray        # (M,) int32     option index the rule agent wanted
    y: np.ndarray        # (M,) float32   game outcome (1 = hero win)
    eps: np.ndarray      # (M,) float32   deviation rate of the run
    game: np.ndarray     # (M,) int32     game cluster id
    split: np.ndarray    # (M,) int8      0 = train, 1 = holdout (by game)

    def __len__(self) -> int:
        return int(self.S.shape[0])

    def opts(self, i: int) -> np.ndarray:
        o, k = int(self.off[i]), int(self.n[i])
        return self.O[o:o + k]

    def p_rule(self) -> np.ndarray:
        """p_b(r | s) -- probability the collector kept the rule pick."""
        return 1.0 - self.eps * (self.n - 1) / self.n

    def p_taken(self) -> np.ndarray:
        """p_b(a | s) for the action actually logged."""
        dev = self.a != self.r
        return np.where(dev, self.eps / self.n, self.p_rule())

    def select(self, mask: np.ndarray) -> "Bandit":
        idx = np.flatnonzero(mask)
        # O has to be re-packed because the kept decisions are not contiguous.
        counts = self.n[idx]
        new_off = np.concatenate(([0], np.cumsum(counts[:-1], dtype=np.int64)))
        O = np.concatenate([self.opts(int(i)) for i in idx]) if len(idx) else \
            np.zeros((0, N_OPTION), dtype=np.float32)
        return Bandit(self.S[idx], O, new_off.astype(np.int64), counts,
                      self.a[idx], self.r[idx], self.y[idx], self.eps[idx],
                      self.game[idx], self.split[idx])


def _game_split(key: str, holdout_frac: float = 0.25) -> int:
    """Deterministic per-game split so train/holdout never share a trajectory."""
    h = 2166136261
    for ch in key.encode():
        h = ((h ^ ch) * 16777619) & 0xFFFFFFFF
    return int((h % 1000) < holdout_frac * 1000)


def load_explore(data_dir: Path, holdout_frac: float = 0.25,
                 eps_keep: tuple[float, ...] | None = None,
                 verbose: bool = True, include_eps0: bool = False) -> Bandit:
    """Pack every eligible decision of the explore log into flat arrays.

    ``eps = 0`` runs are dropped by default and this is not cosmetic:
    with no deviation coin the rule action has propensity 1 and every other
    action has propensity 0, so **positivity fails** and any policy that would
    deviate is unidentified there. Left in, those decisions contribute a
    systematic ``-(y_i - b)`` and corrupt the estimate -- pooling all arms gave
    anti_uniform -7.09pp/decision while the two valid arms gave -5.36 and -4.25.
    """
    files = sorted(data_dir.glob("iono_decisions_*.jsonl"))
    if not files:
        raise SystemExit(f"ERROR: no jsonl under {data_dir}")

    S: list[list[float]] = []
    O: list[list[float]] = []
    off: list[int] = []
    ns: list[int] = []
    aa: list[int] = []
    rr: list[int] = []
    yy: list[float] = []
    ee: list[float] = []
    gg: list[int] = []
    ss: list[int] = []
    gid = 0
    skipped = 0
    n_eps0 = 0

    for fp in files:
        stem = fp.stem
        with fp.open(encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    g = json.loads(line)
                except json.JSONDecodeError:
                    skipped += 1
                    continue
                label = g.get("label", -1)
                if label not in (0, 1):
                    continue  # draw / unfinished carries no outcome signal
                eps = float(g.get("explore_eps", 0.0) or 0.0)
                if eps_keep is not None and eps not in eps_keep:
                    continue
                if eps <= 0.0 and not include_eps0:
                    n_eps0 += 1
                    continue
                sp = _game_split(f"{stem}#{g.get('game')}", holdout_frac)
                gid += 1
                for d in (g.get("decisions") or []):
                    pick = d.get("pick") or []
                    opts = d.get("o") or []
                    # Eligibility must match the collector exactly, otherwise
                    # the propensity formula does not apply to this decision.
                    if len(pick) != 1 or len(opts) <= 1:
                        continue
                    sv = d.get("s") or []
                    if len(sv) != N_STATE or any(len(o) != N_OPTION for o in opts):
                        skipped += 1
                        continue
                    a = int(pick[0])
                    rp = d.get("rp") or []
                    r = int(rp[0]) if rp else a
                    if not (0 <= a < len(opts)) or not (0 <= r < len(opts)):
                        skipped += 1
                        continue
                    off.append(len(O))
                    O.extend(opts)
                    ns.append(len(opts))
                    S.append(sv)
                    aa.append(a)
                    rr.append(r)
                    yy.append(float(label))
                    ee.append(eps)
                    gg.append(gid)
                    ss.append(sp)

    b = Bandit(
        S=np.asarray(S, dtype=np.float32),
        O=np.asarray(O, dtype=np.float32),
        off=np.asarray(off, dtype=np.int64),
        n=np.asarray(ns, dtype=np.int32),
        a=np.asarray(aa, dtype=np.int32),
        r=np.asarray(rr, dtype=np.int32),
        y=np.asarray(yy, dtype=np.float32),
        eps=np.asarray(ee, dtype=np.float32),
        game=np.asarray(gg, dtype=np.int32),
        split=np.asarray(ss, dtype=np.int8),
    )
    if verbose:
        dev = int((b.a != b.r).sum())
        print(f"loaded {len(files)} files: {gid} decided games, {len(b)} eligible "
              f"decisions, {dev} deviations ({100*dev/max(1,len(b)):.2f}%), "
              f"{skipped} skipped, {n_eps0} eps=0 games dropped (positivity)")
        print(f"  holdout: {int((b.split==1).sum())} decisions / "
              f"{len(set(b.game[b.split==1].tolist()))} games")
    return b


# --------------------------------------------------------------------------
# the estimator
# --------------------------------------------------------------------------
def ips_advantage(b: Bandit, pi_prob: np.ndarray, baseline: float | None = None,
                  label: str = "pi") -> dict:
    """A^(pi) vs the rule policy, with game-clustered stderr.

    ``pi_prob[i]`` = pi(a_i | s_i), the candidate policy's probability of the
    action that was actually logged. Deterministic policies pass 0.0 / 1.0.
    """
    m = len(b)
    if m == 0:
        raise ValueError("empty bandit dataset")
    y = b.y.astype(np.float64)
    b0 = float(y.mean()) if baseline is None else float(baseline)

    p_a = b.p_taken().astype(np.float64)
    p_r = b.p_rule().astype(np.float64)
    took_rule = (b.a == b.r).astype(np.float64)

    w = pi_prob.astype(np.float64) / p_a - took_rule / p_r
    c = w * (y - b0)

    # cluster by game: games are iid, decisions inside a game are not
    gids, inv = np.unique(b.game, return_inverse=True)
    per_game = np.bincount(inv, weights=c, minlength=len(gids))
    n_dec_game = np.bincount(inv, minlength=len(gids))
    G = len(gids)

    a_game = float(per_game.mean())                       # per-game total
    se_game = float(per_game.std(ddof=1) / math.sqrt(G)) if G > 1 else float("nan")
    scale = G / m                                         # decisions -> per decision
    a_dec = a_game * scale
    se_dec = se_game * scale

    # Effective sample size of the positive arm: logged deviations that landed on
    # an action the candidate policy would also have taken. A policy with 0 hits
    # is unmeasurable on this data, not "verified equal to tomato".
    hit = int(((b.a != b.r) & (pi_prob > 0)).sum())
    sig = bool(G > 1 and se_game > 0 and abs(a_game) >= 2 * se_game)
    if hit == 0:
        verdict = "UNMEASURABLE"
    elif sig and a_game > 0:
        verdict = "KEEP-CANDIDATE"
    elif sig and a_game < 0:
        verdict = "HARMFUL"
    else:
        verdict = "NULL"

    return {
        "label": label,
        "decisions": m,
        "games": G,
        "eligible_per_game": round(m / G, 2),
        "baseline_y": round(b0, 5),
        "positive_arm_hits": hit,
        "per_decision_pp": round(100 * a_dec, 4),
        "per_decision_se_pp": round(100 * se_dec, 4),
        "per_game_pp": round(100 * a_game, 3),
        "per_game_se_pp": round(100 * se_game, 3),
        "per_game_ci95": [round(100 * (a_game - 1.96 * se_game), 3),
                          round(100 * (a_game + 1.96 * se_game), 3)],
        "significant": sig,
        "verdict": verdict,
        "mean_dec_per_game": round(float(n_dec_game.mean()), 2),
    }


# --------------------------------------------------------------------------
# reference policies, used to validate the estimator against known answers
# --------------------------------------------------------------------------
def prob_tomato(b: Bandit) -> np.ndarray:
    """pi = the rule agent. A^ must be exactly 0."""
    return (b.a == b.r).astype(np.float64)


def prob_uniform(b: Bandit) -> np.ndarray:
    """pi = uniform over all n options."""
    return 1.0 / b.n.astype(np.float64)


def prob_anti_uniform(b: Bandit) -> np.ndarray:
    """pi = uniform over the n-1 NON-rule options.

    This is exactly the intervention the round-2 dose-response measured, so its
    A^ must reproduce the independently measured per-deviation cost.
    """
    nm1 = np.maximum(b.n.astype(np.float64) - 1.0, 1.0)
    return np.where(b.a == b.r, 0.0, 1.0 / nm1)


def prob_from_scores(b: Bandit, scores: np.ndarray) -> np.ndarray:
    """Deterministic argmax policy from a flat per-option score array."""
    out = np.zeros(len(b), dtype=np.float64)
    for i in range(len(b)):
        o, k = int(b.off[i]), int(b.n[i])
        best = int(np.argmax(scores[o:o + k]))
        out[i] = 1.0 if best == int(b.a[i]) else 0.0
    return out


def fmt(res: dict) -> str:
    return (f"{res['label']:>16}  per-game {res['per_game_pp']:+8.3f}pp "
            f"+-{res['per_game_se_pp']:5.3f}  ci95[{res['per_game_ci95'][0]:+.3f},"
            f"{res['per_game_ci95'][1]:+.3f}]  per-dec "
            f"{res['per_decision_pp']:+7.4f}pp  hits={res['positive_arm_hits']:>6}"
            f"  {res['verdict']}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", default="episodes/iono_bc_explore")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--eps", type=float, default=None,
                    help="Restrict to one deviation-rate arm (default: all)")
    ap.add_argument("--split", choices=["all", "train", "holdout"], default="all")
    ap.add_argument("--holdout-frac", type=float, default=0.25)
    ap.add_argument("--ckpt", default=None, help="Score options with this checkpoint")
    ap.add_argument("--build-cache", action="store_true",
                    help="Write the packed arrays to artifacts/ for the trainer")
    ap.add_argument("--include-eps0", action="store_true",
                    help="Keep eps=0 games. Breaks positivity -- diagnostic only.")
    ap.add_argument("--json-out", default="recordings/metrics/iono_ips_ope.json")
    args = ap.parse_args()

    eps_keep = (args.eps,) if args.eps is not None else None
    b = load_explore(ROOT / args.data, args.holdout_frac, eps_keep,
                     include_eps0=args.include_eps0)

    if args.build_cache:
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(CACHE, S=b.S, O=b.O, off=b.off, n=b.n, a=b.a, r=b.r,
                            y=b.y, eps=b.eps, game=b.game, split=b.split)
        print(f"wrote {CACHE} ({CACHE.stat().st_size/1e6:.1f} MB)")

    if args.split != "all":
        want = 1 if args.split == "holdout" else 0
        b = b.select(b.split == want)
        print(f"split={args.split}: {len(b)} decisions")

    out: dict = {"data": args.data, "eps": args.eps, "split": args.split,
                 "results": {}}

    if args.self_test:
        print()
        print("=" * 100)
        print("ESTIMATOR SELF-TEST -- known-answer policies")
        print("=" * 100)
        for name, fn in (("tomato", prob_tomato),
                         ("uniform", prob_uniform),
                         ("anti_uniform", prob_anti_uniform)):
            res = ips_advantage(b, fn(b), label=name)
            out["results"][name] = res
            print(fmt(res))
        print()
        print("  tomato must be exactly 0.000. anti_uniform is the round-2")
        print("  dose-response intervention: its per-deviation number should")
        print("  match the ~-4.2pp/deviation measured from whole-run win rates.")
        au = out["results"]["anti_uniform"]
        print(f"  anti_uniform per-decision = {au['per_decision_pp']:+.4f}pp "
              f"(round-2 whole-run estimate: -4.2pp per deviation)")

    if args.ckpt:
        import torch  # noqa: PLC0415
        ck = torch.load(ROOT / args.ckpt, map_location="cpu", weights_only=False)
        from train_iono_ips_ranker import OptionRanker, apply_norm  # noqa: PLC0415
        net = OptionRanker(**ck["arch"])
        net.load_state_dict(ck["state_dict"])
        net.eval()
        rep = np.repeat(np.arange(len(b)), b.n.astype(np.int64))
        with torch.no_grad():
            s = torch.from_numpy(apply_norm(b.S[rep], ck["s_mean"], ck["s_std"]))
            o = torch.from_numpy(apply_norm(b.O, ck["o_mean"], ck["o_std"]))
            scores = net(s, o).numpy()
        pi_prob = prob_from_scores(b, scores)
        res = ips_advantage(b, pi_prob, label=Path(args.ckpt).stem)
        # How often the learned argmax differs from the rule pick: a policy that
        # never disagrees is trivially A^ = 0 and is not an improvement.
        argmax_is_rule = np.zeros(len(b), dtype=bool)
        for i in range(len(b)):
            o, k = int(b.off[i]), int(b.n[i])
            argmax_is_rule[i] = int(np.argmax(scores[o:o + k])) == int(b.r[i])
        res["agree_with_tomato_pct"] = round(100 * float(argmax_is_rule.mean()), 2)
        out["results"]["ckpt"] = res
        print()
        print("=" * 100)
        print(f"CANDIDATE RE-RANKER -- {args.ckpt}  (split={args.split})")
        print("=" * 100)
        print(fmt(res))
        print(f"  agrees with tomato on {res['agree_with_tomato_pct']:.2f}% of "
              f"eligible decisions")
        print(f"  KEEP-CANDIDATE requires per_game >= 2*se "
              f"({2*res['per_game_se_pp']:.3f}pp); measured {res['per_game_pp']:+.3f}pp")

    dst = ROOT / args.json_out
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"\nwrote {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
